language: scala
sudo: false
before_install: umask 0022
scala:
  - 2.10.7

cache:
directories:
  - $HOME/.m2/repository
  - $HOME/.sbt
  - $HOME/.ivy2

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION -Dakka.test.timefactor=1.5 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' test

# Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

jdk:
  - oraclejdk8
  - openjdk8

notifications:
  email:
  - irfan.ansari@applyingagile.com